export enum Tools {
  Aerosol = 'aerosol',
  Arrow = 'arrow',
  Brush = 'brush',
  Bucket = 'bucket',
  ColorApplicator = 'colorApplicator',
  Ellipse = 'ellipse',
  Eraser = 'eraser',
  Feather = 'feather',
  Grid = 'grid',
  Line = 'line',
  None = 'none',
  Pencil = 'pencil',
  Pipette = 'pipette',
  Polygon = 'polygon',
  Rectangle = 'rectangle',
  Selection = 'selection',
  Stamp = 'stamp',
  Text = 'text'
}
